---
title: "Group Document"
format: html
editor: visual
---

# Adomas

```{r}
library(tidyverse)

b <- 2
a <- b*7

```

## New Feature

```{r}
# The code base for the new feature
x <- sin(5)
```

# Chuang

```{r}
"Sub is the best captain" |> 
  print()
```

```{r}
# Load tidyverse
library(tidyverse)

# Define colors
saffron <- "#FF9933"
white <- "#FFFFFF"
green <- "#138808"
navy_blue <- "#000080"

# Create a dataframe to define layers for colors
flag <- data.frame(
  xmin = c(0, 0, 0),
  xmax = c(10, 10, 10),
  ymin = c(0, 5, 10),
  ymax = c(5, 10, 15),
  color = c(green, white, saffron)
)

# Basic plot
p <- ggplot() +
  geom_rect(data = flag, 
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = color),
            color = "black") +
  coord_fixed(ratio = 1) +
  theme_void() +
  theme(legend.position = "none")

# Adding the Ashoka Chakra
p <- p + 
  geom_polygon(data = data.frame(x = c(5, 5.5, 5), y = c(10, 10, 10.5)), 
               aes(x, y), 
               fill = navy_blue,
               color = navy_blue) +
  geom_polygon(data = data.frame(x = c(5, 5.5, 5), y = c(10, 10, 9.5)), 
               aes(x, y), 
               fill = navy_blue,
               color = navy_blue)

# 24 spokes in the Chakra
for(angle in seq(0, 360-15, by = 15)){
  x = 5 + 0.5 * cos(angle * pi / 180)
  y = 10 + 0.5 * sin(angle * pi / 180)
  
  p <- p + geom_line(aes(x = c(5, x), y = c(10, y)), color = navy_blue)
}

# Display flag
print(p)

```

# Subhayan

```{r}

#| echo: false

library(tidyverse)

list5 <- c("Subh", "Emmanuel", "Chuang", "Reka", "Adomas")

list5
```

## New Analysis

```{r}
a <- 5
b <- 7
a + b
```

# Reka


```{r}
library(tidyverse)

xy <- seq(from = -3,
          to = 3, 
          by = 0.01)
expand.grid(x = xy,
            y = xy) |>
  ggplot(
    mapping = aes(
      x = (1 - x - sin(y^2)),
      y = (1 + y - cos(x^2)))) +
  geom_point(alpha = 0.05,
             shape = 20,
             size = 0) +
  theme_void() +
  coord_polar()
```
>>>>>>> main

# Emmanuel

Loading tidyverse

```{r}
#| eval: FALSE
library(tidyverse)
```

Plotting for the diamonds dataset

```{r}
diamonds |> 
	filter(x*y*z<1000) |> 
	ggplot(aes(x=x*y*z, y=price)) + 
	geom_point(aes(color=color)) +
	labs(title="Relation between volume and price in the diamonds dataset (stratified on the color)", x="Volume of the diamond", y="Price of the diamond")
```

Added markdown

```{r}
diamonds |> 
	filter(x*y*z<1000) |> 
	ggplot(aes(x=x*y*z, y=price)) + 
	geom_point(aes(color=color)) +
	facet_grid(~color) +
  ylim(c(0,20000)) +
  geom_smooth(aes(color=color), method='lm')
	labs(title="Relation between volume and price in the diamonds dataset (stratified on the color)", x="Volume of the diamond", y="Price of the diamond")
```
